--- 
kind: pipeline
name: test-deploy
steps: 
  - 
    commands: 
      - "go get github.com/beego/bee"
      - "go get github.com/astaxie/beego"
      - "cd /go/src/test-deployment"
      - "bee pack"
    image: "golang:latest"
    name: build

