workspace:
  base: /go
  path: src/github.com/arca1n/test-deployment

pipeline:
  build:
    image: golang:latest
    commands:
      - go get github.com/beego/bee
      - go get github.com/astaxie/beego
      - bee pack
