workspace:
  base: /go
  path: src/test-deployment

pipeline:
  build:
    image: golang:latest
    commands:
      - go get github.com/beego/bee
      - go get github.com/astaxie/beego
      - cd /go/src/test-deployment
      - bee pack
