--- 
kind: pipeline
name: test-deploy
steps: 
  - 
    commands: 
      - "go get github.com/beego/bee"
      - "go get github.com/astaxie/beego"
      - "cd /go/src/test-deployment"
      - "bee pack"
    image: "golang:latest"
    name: build
  - 
    image: plugins/slack
    name: slack
    settings: 
      channel: build-status
      template: |-
          {{#success build.status}}
            build {{build.number}} succeeded. Good job.
          {{else}}
            build {{build.number}} failed. Fix me please.
          {{/success}}
      webhook: "https://hooks.slack.com/services/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"
workspace: 
  base: /go
  path: src/test-deployment
